<a href="https://colab.research.google.com/github/tirth4077-byte/ML-Lab/blob/main/mlpr3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# load the iris dataset from sklearn
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
feature_names  = iris.feature_names
print("Initial shape of the dataset:",X.shape)

Initial shape of the dataset: (150, 4)


In [6]:
# Standardization of the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#Covariance matrix
cov_matrix = np.cov(X_scaled.T)
print("Covariance matrix shape:",cov_matrix.shape)

Covariance matrix shape: (4, 4)


In [8]:
# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:\n",eigenvalues)
print("Eigenvectors shape :\n",eigenvectors.shape)


Eigenvalues:
 [2.93808505 0.9201649  0.14774182 0.02085386]
Eigenvectors shape :
 (4, 4)


In [10]:
# Sort Eigenvalues and Eigenvectors
sorted_index = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_index]
sorted_eigenvectors = eigenvectors[:,sorted_index]

In [11]:
#Calculate explained variance ratio
explained_variance_ratio = sorted_eigenvalues / np.sum(sorted_eigenvalues)

print("\nExplained Variance Ratio:")
for i, var in enumerate(explained_variance_ratio):
    print(f"Principal Component {i+1}: {var:.2f}")


Explained Variance Ratio:
Principal Component 1: 0.73
Principal Component 2: 0.23
Principal Component 3: 0.04
Principal Component 4: 0.01


In [12]:
# select top k elements
k = 7
top_k_eigenvectors = sorted_eigenvectors[:,:k]


In [13]:
# Data Projection
X_pca = X_scaled.dot(top_k_eigenvectors)

print("Shape after PCA transformation:",X_pca.shape)
print("first 5 rows of transformed data:",X_pca[:5])

Shape after PCA transformation: (150, 4)
first 5 rows of transformed data: [[-2.26470281 -0.4800266  -0.12770602  0.0241682 ]
 [-2.08096115  0.67413356 -0.23460885  0.10300677]
 [-2.36422905  0.34190802  0.04420148  0.02837705]
 [-2.29938422  0.59739451  0.09129011 -0.06595556]
 [-2.38984217 -0.64683538  0.0157382  -0.03592281]]
